const {
  formatAiProviderLabel,
  formatCategorySourceLabel,
  formatDraftProviderNotice,
} = require('../public/ai-provider-helpers');

test('formatAiProviderLabel includes provider when AI priority exists', () => {
  expect(formatAiProviderLabel({ aiPriority: 'respond-now', aiProviderUsed: 'claude-opus' })).toBe('respond-now (claude-opus)');
});

test('formatAiProviderLabel returns unavailable when no AI priority exists', () => {
  expect(formatAiProviderLabel({ aiPriority: '', aiProviderUsed: '' })).toBe('Unavailable');
});

test('formatAiProviderLabel shows heuristic-only when no AI classifier fields exist', () => {
  expect(formatAiProviderLabel({ recommendedAction: 'Review Later', categorySource: 'custom_rule' })).toBe('Heuristic only');
});

test('formatDraftProviderNotice uses fallback label when provider is missing', () => {
  expect(formatDraftProviderNotice({})).toBe('Draft generated by unknown provider.');
});

test('formatDraftProviderNotice includes the provider used', () => {
  expect(formatDraftProviderNotice({ providerUsed: 'gemma-lmstudio' })).toBe('Draft generated by gemma-lmstudio.');
});

test('formatCategorySourceLabel shows AI when category came from classifier output', () => {
  expect(formatCategorySourceLabel({ categorySource: 'ai' })).toBe('AI');
});

test('formatCategorySourceLabel shows heuristic fallback when category came from local derivation', () => {
  expect(formatCategorySourceLabel({ categorySource: 'heuristic' })).toBe('Heuristic fallback');
});

test('formatCategorySourceLabel shows custom rule source', () => {
  expect(formatCategorySourceLabel({ categorySource: 'custom_rule' })).toBe('Custom rule');
});

test('formatCategorySourceLabel shows topic label source', () => {
  expect(formatCategorySourceLabel({ categorySource: 'topic_label' })).toBe('Topic label');
});

test('formatCategorySourceLabel shows unknown when source is missing', () => {
  expect(formatCategorySourceLabel({})).toBe('Unknown');
});